#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"

SWARM_DIR="$ROOT_DIR/swarm/stacks"
COMPOSE_DIR="$ROOT_DIR/compose"

ENV_FILE="$ROOT_DIR/docker.env.example"
OUTPUT="$SCRIPT_DIR/resources.toml"

SERVER="asteri-is"
SWARM="asteri"

GIT_PROVIDER="github.com"
GIT_ACCOUNT="gmnds"
REPO="gmnds/docker-infra"
BRANCH="main"

# Resources que devem existir no Komodo,
# mas não devem ser deployados automaticamente.
NO_AUTO_DEPLOY=(
    "portainer"
)

declare -a GLOBAL_ENV_KEYS=()
declare -A GLOBAL_ENV_VALUES=()

#
# Helpers
#

trim() {
    local value="$1"

    value="${value#"${value%%[![:space:]]*}"}"
    value="${value%"${value##*[![:space:]]}"}"

    printf '%s' "$value"
}

toml_escape() {
    local value="$1"

    value="${value//\\/\\\\}"
    value="${value//\"/\\\"}"

    printf '%s' "$value"
}

load_global_env() {
    if [ ! -f "$ENV_FILE" ]; then
        echo "Erro: arquivo não encontrado: $ENV_FILE" >&2
        exit 1
    fi

    local raw
    local line
    local key
    local value

    while IFS= read -r raw || [ -n "$raw" ]; do
        line="$(trim "$raw")"

        # Ignora vazios e comentários
        [ -z "$line" ] && continue
        [[ "$line" == \#* ]] && continue

        if [[ "$line" != *=* ]]; then
            echo "Erro em $ENV_FILE: linha inválida:" >&2
            echo "  $raw" >&2
            exit 1
        fi

        key="$(trim "${line%%=*}")"
        value="$(trim "${line#*=}")"

        if [[ ! "$key" =~ ^[A-Za-z_][A-Za-z0-9_]*$ ]]; then
            echo "Erro em $ENV_FILE: variável inválida: $key" >&2
            exit 1
        fi

        # Remove aspas externas simples ou duplas.
        if [[ "$value" =~ ^\".*\"$ ]]; then
            value="${value:1:${#value}-2}"
        elif [[ "$value" =~ ^\'.*\'$ ]]; then
            value="${value:1:${#value}-2}"
        fi

        # Evita duplicatas.
        if [[ -z "${GLOBAL_ENV_VALUES[$key]+x}" ]]; then
            GLOBAL_ENV_KEYS+=("$key")
        fi

        GLOBAL_ENV_VALUES["$key"]="$value"
    done < "$ENV_FILE"
}

validate_global_env() {
    if [[ -z "${GLOBAL_ENV_VALUES[DOCKER_ROOT]+x}" ]]; then
        echo "Erro: DOCKER_ROOT não está definido em:" >&2
        echo "  $ENV_FILE" >&2
        exit 1
    fi

    if [[ -z "${GLOBAL_ENV_VALUES[DOCKER_ROOT]}" ]]; then
        echo "Erro: DOCKER_ROOT está vazio." >&2
        exit 1
    fi

    # Neste layout os YAMLs usam:
    #
    #   ${DOCKER_ROOT}/volumes/...
    #
    # Portanto DOCKER_ROOT deve ser /srv/docker,
    # e não /srv/docker/volumes.
    if [[ "${GLOBAL_ENV_VALUES[DOCKER_ROOT]}" == */volumes ]]; then
        echo "Erro: DOCKER_ROOT deve apontar para a raiz Docker." >&2
        echo >&2
        echo "Atual: ${GLOBAL_ENV_VALUES[DOCKER_ROOT]}" >&2
        echo "Esperado, por exemplo: /srv/docker" >&2
        exit 1
    fi
}

should_auto_deploy() {
    local name="$1"
    local excluded

    for excluded in "${NO_AUTO_DEPLOY[@]}"; do
        if [ "$name" = "$excluded" ]; then
            return 1
        fi
    done

    return 0
}

find_stack_files() {
    local dir="$1"
    local -n result="$2"

    result=()

    # Arquivo principal preferencial
    if [ -f "$dir/stack.yaml" ]; then
        result=("stack.yaml")
        return
    fi

    if [ -f "$dir/stack.yml" ]; then
        result=("stack.yml")
        return
    fi

    if [ -f "$dir/compose.yaml" ]; then
        result=("compose.yaml")
        return
    fi

    if [ -f "$dir/compose.yml" ]; then
        result=("compose.yml")
        return
    fi

    # Ex.: Chatwoot com múltiplos YAML/YML.
    while IFS= read -r file; do
        result+=("$(basename "$file")")
    done < <(
        find "$dir" \
            -maxdepth 1 \
            -type f \
            \( -name '*.yaml' -o -name '*.yml' \) \
            | sort
    )
}

write_global_variables() {
    local key
    local value

    printf '# Generated by komodo/generate-resources.sh\n' >> "$OUTPUT"
    printf '# DO NOT EDIT MANUALLY\n\n' >> "$OUTPUT"

    for key in "${GLOBAL_ENV_KEYS[@]}"; do
        value="$(toml_escape "${GLOBAL_ENV_VALUES[$key]}")"

        printf '[[variable]]\n' >> "$OUTPUT"
        printf 'name = "%s"\n' "$key" >> "$OUTPUT"
        printf 'value = "%s"\n\n' "$value" >> "$OUTPUT"
    done
}

write_stack_environment() {
    local key

    printf 'environment = """\n' >> "$OUTPUT"

    for key in "${GLOBAL_ENV_KEYS[@]}"; do
        printf '%s = [[%s]]\n' "$key" "$key" >> "$OUTPUT"
    done

    printf '"""\n' >> "$OUTPUT"
}

generate_stack() {
    local dir="$1"
    local target_type="$2"
    local target="$3"

    local name
    local relative_dir
    local files=()

    name="$(basename "$dir")"
    relative_dir="${dir#"$ROOT_DIR"/}"

    find_stack_files "$dir" files

    if [ "${#files[@]}" -eq 0 ]; then
        echo "Ignorando '$relative_dir': nenhum YAML/YML encontrado." >&2
        return
    fi

    printf '[[stack]]\n' >> "$OUTPUT"
    printf 'name = "%s"\n' "$name" >> "$OUTPUT"

    if should_auto_deploy "$name"; then
        printf 'deploy = true\n' >> "$OUTPUT"
    else
        printf 'deploy = false\n' >> "$OUTPUT"
    fi

    printf '[stack.config]\n' >> "$OUTPUT"

    case "$target_type" in
        server)
            printf 'server = "%s"\n' "$target" >> "$OUTPUT"
            ;;
        swarm)
            printf 'swarm = "%s"\n' "$target" >> "$OUTPUT"
            ;;
        *)
            echo "Target inválido para '$name': $target_type" >&2
            exit 1
            ;;
    esac

    printf 'git_provider = "%s"\n' "$GIT_PROVIDER" >> "$OUTPUT"
    printf 'git_account = "%s"\n' "$GIT_ACCOUNT" >> "$OUTPUT"
    printf 'repo = "%s"\n' "$REPO" >> "$OUTPUT"
    printf 'branch = "%s"\n' "$BRANCH" >> "$OUTPUT"
    printf 'run_directory = "%s"\n' "$relative_dir" >> "$OUTPUT"

    printf 'file_paths = [' >> "$OUTPUT"

    local first=true
    local file

    for file in "${files[@]}"; do
        if "$first"; then
            first=false
        else
            printf ', ' >> "$OUTPUT"
        fi

        printf '"%s"' "$file" >> "$OUTPUT"
    done

    printf ']\n' >> "$OUTPUT"

    # Injeta todas as variáveis globais no ambiente utilizado
    # para interpolar os arquivos Compose/Stack.
    write_stack_environment

    printf '\n' >> "$OUTPUT"
}

#
# Main
#

load_global_env
validate_global_env

: > "$OUTPUT"

write_global_variables

#
# Docker Compose
#
if [ -d "$COMPOSE_DIR" ]; then
    for dir in "$COMPOSE_DIR"/*; do
        [ -d "$dir" ] || continue

        name="$(basename "$dir")"

        # Komodo é bootstrap e não gerencia a si próprio.
        if [ "$name" = "komodo" ]; then
            continue
        fi

        generate_stack "$dir" "server" "$SERVER"
    done
fi

#
# Docker Swarm
#
if [ -d "$SWARM_DIR" ]; then
    for dir in "$SWARM_DIR"/*; do
        [ -d "$dir" ] || continue

        generate_stack "$dir" "swarm" "$SWARM"
    done
fi

echo "Gerado: $OUTPUT"
echo
echo "Variáveis globais:"
for key in "${GLOBAL_ENV_KEYS[@]}"; do
    echo "  $key=${GLOBAL_ENV_VALUES[$key]}"
done
