[[server]]
name = "asteri-c"
[server.config]
enabled = true

##

[[server]]
name = "asteri-is"
[server.config]
enabled = true

##

[[server]]
name = "asteri-m"
[server.config]
enabled = true

##

[[server]]
name = "asteri-mm"
[server.config]
enabled = true

##

[[swarm]]
name = "asteri"
[swarm.config]
servers = ["asteri-is"]
send_unhealthy_alerts = true

##

[[stack]]
name = "adguard"
deploy = true
[stack.config]
swarm = "asteri"
git_account = "gmnds"
repo = "gmnds/docker-infra"
run_directory = "swarm/stacks/adguard"
file_paths = ["stack.yml"]
environment = """
PUID = [[PUID]]
PGID = [[PGID]]
TZ = [[TZ]]
DOCKER_ROOT = [[DOCKER_ROOT]]
DOMAIN = [[DOMAIN]]
"""

##

[[stack]]
name = "asteri-auth"
deploy = true
[stack.config]
server = "asteri-is"
git_account = "gmnds"
repo = "gmnds/docker-infra"
run_directory = "compose/asteri-auth"
file_paths = ["compose.yaml"]
environment = """
PUID = [[PUID]]
PGID = [[PGID]]
TZ = [[TZ]]
DOCKER_ROOT = [[DOCKER_ROOT]]
DOMAIN = [[DOMAIN]]
"""

##

[[stack]]
name = "beszel"
deploy = true
[stack.config]
swarm = "asteri"
git_account = "gmnds"
repo = "gmnds/docker-infra"
run_directory = "swarm/stacks/beszel"
file_paths = ["stack.yaml"]
environment = """
PUID = [[PUID]]
PGID = [[PGID]]
TZ = [[TZ]]
DOCKER_ROOT = [[DOCKER_ROOT]]
DOMAIN = [[DOMAIN]]
"""

##

[[stack]]
name = "chatwoot"
deploy = true
[stack.config]
swarm = "asteri"
git_account = "gmnds"
repo = "gmnds/docker-infra"
run_directory = "swarm/stacks/chatwoot"
file_paths = [
  "chatwoot.yml",
  "ev.yml",
  "pg.yml",
  "redis.yml"
]
environment = """
PUID = [[PUID]]
PGID = [[PGID]]
TZ = [[TZ]]
DOCKER_ROOT = [[DOCKER_ROOT]]
DOMAIN = [[DOMAIN]]
"""

##

[[stack]]
name = "dokploy"
deploy = true
[stack.config]
swarm = "asteri"
git_account = "gmnds"
repo = "gmnds/docker-infra"
run_directory = "swarm/stacks/dokploy"
file_paths = ["stack.yml"]
environment = """
PUID = [[PUID]]
PGID = [[PGID]]
TZ = [[TZ]]
DOCKER_ROOT = [[DOCKER_ROOT]]
DOMAIN = [[DOMAIN]]
"""

##

[[stack]]
name = "forgejo"
deploy = true
[stack.config]
swarm = "asteri"
git_account = "gmnds"
repo = "gmnds/docker-infra"
run_directory = "swarm/stacks/forgejo"
file_paths = ["stack.yaml"]
environment = """
PUID = [[PUID]]
PGID = [[PGID]]
TZ = [[TZ]]
DOCKER_ROOT = [[DOCKER_ROOT]]
DOMAIN = [[DOMAIN]]
"""

##

[[stack]]
name = "gossip-girl"
deploy = true
[stack.config]
swarm = "asteri"
git_account = "gmnds"
repo = "gmnds/docker-infra"
run_directory = "swarm/stacks/gossip-girl"
file_paths = ["stack.yaml"]
environment = """
PUID = [[PUID]]
PGID = [[PGID]]
TZ = [[TZ]]
DOCKER_ROOT = [[DOCKER_ROOT]]
DOMAIN = [[DOMAIN]]
"""

##

[[stack]]
name = "jellyfin"
deploy = true
[stack.config]
swarm = "asteri"
git_account = "gmnds"
repo = "gmnds/docker-infra"
run_directory = "swarm/stacks/jellyfin"
file_paths = ["stack.yaml"]
environment = """
PUID = [[PUID]]
PGID = [[PGID]]
TZ = [[TZ]]
DOCKER_ROOT = [[DOCKER_ROOT]]
DOMAIN = [[DOMAIN]]
"""

##

[[stack]]
name = "mosquitto"
deploy = true
[stack.config]
swarm = "asteri"
git_account = "gmnds"
repo = "gmnds/docker-infra"
run_directory = "swarm/stacks/mosquitto"
file_paths = ["stack.yaml"]
environment = """
PUID = [[PUID]]
PGID = [[PGID]]
TZ = [[TZ]]
DOCKER_ROOT = [[DOCKER_ROOT]]
DOMAIN = [[DOMAIN]]
"""

##

[[stack]]
name = "n8n"
[stack.config]
swarm = "asteri"
git_account = "gmnds"
repo = "gmnds/docker-infra"
run_directory = "swarm/stacks/n8n"
file_paths = ["stack.yaml"]
environment = """
PUID = [[PUID]]
PGID = [[PGID]]
TZ = [[TZ]]
DOCKER_ROOT = [[DOCKER_ROOT]]
DOMAIN = [[DOMAIN]]
"""

##

[[stack]]
name = "portainer"
[stack.config]
swarm = "asteri"
git_account = "gmnds"
repo = "gmnds/docker-infra"
run_directory = "swarm/stacks/portainer"
file_paths = ["stack.yaml"]
environment = """
PUID = [[PUID]]
PGID = [[PGID]]
TZ = [[TZ]]
DOCKER_ROOT = [[DOCKER_ROOT]]
DOMAIN = [[DOMAIN]]
"""

##

[[stack]]
name = "proxy"
deploy = true
[stack.config]
swarm = "asteri"
git_account = "gmnds"
repo = "gmnds/docker-infra"
run_directory = "swarm/stacks/proxy"
file_paths = ["stack.yaml"]
environment = """
PUID=[[PUID]]
PGID=[[PGID]]
TZ=[[TZ]]
DOCKER_ROOT=[[DOCKER_ROOT]]
DOMAIN=[[DOMAIN]]
"""

##

[[stack]]
name = "rustfs"
deploy = true
[stack.config]
swarm = "asteri"
git_account = "gmnds"
repo = "gmnds/docker-infra"
run_directory = "swarm/stacks/rustfs"
file_paths = ["stack.yaml"]
environment = """
PUID = [[PUID]]
PGID = [[PGID]]
TZ = [[TZ]]
DOCKER_ROOT = [[DOCKER_ROOT]]
DOMAIN = [[DOMAIN]]
"""

##

[[stack]]
name = "vaultwarden"
deploy = true
[stack.config]
swarm = "asteri"
git_account = "gmnds"
repo = "gmnds/docker-infra"
run_directory = "swarm/stacks/vaultwarden"
file_paths = ["stack.yaml"]
environment = """
PUID = [[PUID]]
PGID = [[PGID]]
TZ = [[TZ]]
DOCKER_ROOT = [[DOCKER_ROOT]]
DOMAIN = [[DOMAIN]]
"""

##

[[repo]]
name = "astrum-stack"
[repo.config]
server = "asteri-is"
git_https = false
git_account = "gmnds"
repo = "GMNDS/docker-infra"
path = "/srv/docker/repos"

##

[[procedure]]
name = "Backup Core Database"
description = "Triggers the Core database backup at the scheduled time."
tags = ["system"]
config.schedule = "Every day at 01:00"

[[procedure.config.stage]]
name = "Stage 1"
enabled = true
executions = [
  { execution.type = "BackupCoreDatabase", execution.params = {}, enabled = true }
]

##

[[procedure]]
name = "Global Auto Update"
description = "Pulls and auto updates Stacks and Deployments using 'poll_for_updates' or 'auto_update'."
tags = ["system"]
config.schedule = "Every day at 03:00"

[[procedure.config.stage]]
name = "Stage 1"
enabled = true
executions = [
  { execution.type = "GlobalAutoUpdate", execution.params.skip_auto_update = false, enabled = true }
]

##

[[procedure]]
name = "Rotate Server Keys"
description = "Rotates all currently connected Server keys."
tags = ["system"]
config.schedule = "Every day at 06:00"

[[procedure.config.stage]]
name = "Stage 1"
enabled = true
executions = [
  { execution.type = "RotateAllServerKeys", execution.params = {}, enabled = true }
]

##

[[resource_sync]]
name = "git-infra"
[resource_sync.config]
linked_repo = "astrum-stack"
resource_path = ["komodo/resources.toml"]
managed = true
include_variables = true

##

[[variable]]
name = "DOCKER_ROOT"
value = "/srv/docker"
is_secret = false

##

[[variable]]
name = "DOMAIN"
value = "astrum.app.br"
is_secret = false

##

[[variable]]
name = "PGID"
value = "1002"
is_secret = false

##

[[variable]]
name = "PUID"
value = "1002"
is_secret = false

##

[[variable]]
name = "TZ"
value = "America/Sao_Paulo"
is_secret = false