[[stack]]
name = "adguard"
[stack.config]
swarm = "asteri"
git_provider = "github.com"
git_account = "gmnds"
repo = "gmnds/docker-infra"
branch = "main"
run_directory = "swarm/stacks/adguard"
file_paths = ["stack.yml"]

[[stack]]
name = "beszel"
[stack.config]
swarm = "asteri"
git_provider = "github.com"
git_account = "gmnds"
repo = "gmnds/docker-infra"
branch = "main"
run_directory = "swarm/stacks/beszel"
file_paths = ["stack.yaml"]

[[stack]]
name = "chatwoot"
[stack.config]
swarm = "asteri"
git_provider = "github.com"
git_account = "gmnds"
repo = "gmnds/docker-infra"
branch = "main"
run_directory = "swarm/stacks/chatwoot"
file_paths = ["chatwoot.yml", "ev.yml", "migrate.yml", "pg.yml", "redis.yml"]

[[stack]]
name = "dokploy"
[stack.config]
swarm = "asteri"
git_provider = "github.com"
git_account = "gmnds"
repo = "gmnds/docker-infra"
branch = "main"
run_directory = "swarm/stacks/dokploy"
file_paths = ["stack.yml"]

[[stack]]
name = "forgejo"
[stack.config]
swarm = "asteri"
git_provider = "github.com"
git_account = "gmnds"
repo = "gmnds/docker-infra"
branch = "main"
run_directory = "swarm/stacks/forgejo"
file_paths = ["stack.yaml"]

[[stack]]
name = "gossip-girl"
[stack.config]
swarm = "asteri"
git_provider = "github.com"
git_account = "gmnds"
repo = "gmnds/docker-infra"
branch = "main"
run_directory = "swarm/stacks/gossip-girl"
file_paths = ["stack.yaml"]

[[stack]]
name = "mosquitto"
[stack.config]
swarm = "asteri"
git_provider = "github.com"
git_account = "gmnds"
repo = "gmnds/docker-infra"
branch = "main"
run_directory = "swarm/stacks/mosquitto"
file_paths = ["stack.yaml"]

[[stack]]
name = "n8n"
[stack.config]
swarm = "asteri"
git_provider = "github.com"
git_account = "gmnds"
repo = "gmnds/docker-infra"
branch = "main"
run_directory = "swarm/stacks/n8n"
file_paths = ["stack.yaml"]

[[stack]]
name = "portainer"
[stack.config]
swarm = "asteri"
git_provider = "github.com"
git_account = "gmnds"
repo = "gmnds/docker-infra"
branch = "main"
run_directory = "swarm/stacks/portainer"
file_paths = ["stack.yaml"]

[[stack]]
name = "rustfs"
[stack.config]
swarm = "asteri"
git_provider = "github.com"
git_account = "gmnds"
repo = "gmnds/docker-infra"
branch = "main"
run_directory = "swarm/stacks/rustfs"
file_paths = ["stack.yaml"]

[[stack]]
name = "traefik"
[stack.config]
swarm = "asteri"
git_provider = "github.com"
git_account = "gmnds"
repo = "gmnds/docker-infra"
branch = "main"
run_directory = "swarm/stacks/traefik"
file_paths = ["stack.yaml"]

[[stack]]
name = "vaultwarden"
[stack.config]
swarm = "asteri"
git_provider = "github.com"
git_account = "gmnds"
repo = "gmnds/docker-infra"
branch = "main"
run_directory = "swarm/stacks/vaultwarden"
file_paths = ["stack.yaml"]

