version: "3.9"

secrets:
  dokploy_postgres_password:
    external: true

services:
  dokploy-postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: dokploy
      POSTGRES_DB: dokploy
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    secrets:
      - source: dokploy_postgres_password
        target: postgres_password
    volumes:
      - dokploy-postgres:/var/lib/postgresql/data
    networks:
      - dokploy-network
    deploy:
      placement:
        constraints:
          - node.role == manager

  dokploy-redis:
    image: redis:7
    volumes:
      - dokploy-redis:/data
    networks:
      dokploy-network:
          aliases:
            - dokploy-redis
    deploy:
      placement:
        constraints:
          - node.role == manager

  dokploy:
    image: dokploy/dokploy:latest
    # ports:
      # - target: 3000
        # published: 3000
        # mode: host
    environment:
      TZ: America/Sao_Paulo
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      # NODE_ENV: production
      # FORCE_COLOR: "1"
      # NODE_OPTIONS: "--enable-source-maps"
      # NPM_CONFIG_LOGLEVEL: info
      ADVERTISE_ADDR: 10.13.14.1
      # REDIS_URL: redis://redis:6379
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/dokploy:/etc/dokploy
      - ${DOCKER_ROOT}/volumes/traefik/traefik.yml:/etc/dokploy/traefik/traefik.yml
      - ${DOCKER_ROOT}/volumes/traefik/dynamic:/etc/dokploy/traefik/dynamic
    secrets:
      - source: dokploy_postgres_password
        target: postgres_password
    networks:
      - traefik_proxy
      - dokploy-network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        # com.docker.swarm.stdout: "true"
        # com.docker.swarm.service.name: dokploy
        com.dokploy.app: dokploy
        traefik.enable: "true"
        traefik.http.routers.dokploy.rule: Host(`dokploy.astrum.app.br`)
        traefik.http.routers.dokploy.entrypoints: websecure
        traefik.http.routers.dokploy.tls: "true"
        traefik.http.services.dokploy.loadbalancer.server.port: "3000"

volumes:
  dokploy-postgres:
    external: true
  dokploy-redis:
    external: true

networks:
  traefik_proxy:
    external: true

  dokploy-network:
    external: true
