services:

  jellyfin:
    image: linuxserver/jellyfin:10.11.11

    environment:
      - PUID=1002
      - PGID=1002
      - TZ=America/Sao_Paulo

    volumes:
      - ${DOCKER_ROOT}/jellyfin:/config
      - /asteri/media:/media

    networks:
      - traefik_proxy

    deploy:
      replicas: 1

      placement:
        constraints:
          - node.labels.media == true

      restart_policy:
        condition: any

      labels:
        - traefik.enable=true
        - traefik.swarm.network=traefik_proxy

        - traefik.http.routers.jellyfin.rule=Host(`midia.astrum.app.br`)
        - traefik.http.routers.jellyfin.entrypoints=websecure
        - traefik.http.routers.jellyfin.tls=true

        - traefik.http.services.jellyfin.loadbalancer.server.port=8096

networks:
  traefik_proxy:
    external: true

